version: '3'
services:
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./runner.toml:/etc/gitlab-runner/config.toml
    networks:
      - gitlab-network

networks:
  gitlab-network:
